# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7c4fb4269e272b056e40a3549829d028cb1df3dcbc15e1378e03f939cf623396a67a774cd171dc399d73e81b06b3cc3082fb5d76fdfd651a1c60631e32cd4aa

test:
  secret_key_base: c01b9a700b42f78813febc63ac3028a2ce8e0b756f1a849e03c3aeceee84c005ac8e141401c570ced1b291a78985acdd07804cd6995c75468b75508474d6584a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
